# Generated by Django 2.2.5 on 2019-09-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert', '0001_initial'),
        ('base', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expert.Expert')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.Vacancy')),
            ],
            options={
                'unique_together': {('expert', 'employee', 'vacancy')},
            },
        ),
    ]
