# Generated by Django 2.2.5 on 2019-09-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='StaffOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_orders', to='base.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dead_line', models.DateTimeField(null=True, verbose_name='dead line')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='base.Position')),
                ('staff_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert.StaffOrder')),
            ],
        ),
        migrations.CreateModel(
            name='TodoListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Skill')),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.Position')),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Position')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='skills',
            field=models.ManyToManyField(to='base.Skill'),
        ),
    ]
